### PR TITLE
Fix left/right key movement to move by column

### LINKED ISSUE #50: Left/right key press should move basket -/+1 column
Needs:
- calculate size of 1 column in percentage of play area
- update existing mutators for move left/right

### PR DESCRIPTION
**Pull request by poltak**
- The resulting xPos from left/right key movements should now always place the basket in the center of a column.
- if mouse movement moves basket outside of a column, the next left/right key movement should move it to the nearest column.
- Fixes #50

### CODE REVIEW

**Comment by tranhuuphucuong** [comment]
I noticed on my laptop the basket is not really in the center of the column, haven't figure out why yet

image

**Comment by poltak** [comment]
Dang, yeah I can reproduce. It was tricky. I think it's to do with the basket width being sized while the columns are responsively sized. Maybe we can make the basket width responsive too?

I'll look at this with a fresh mind again later

**Comment by tranhuuphucuong** [comment]
It works like a charm now, I basically used a new state called `columnsXPos` that got all the columns xPos on the initial dom render. Fixed #51 also

**Comment by poltak** [comment]
Thanks Cuong!!! This makes the game feel so much better to play :D I'll check out the code properly later today, and hopefully merge this tonight

**Comment by poltak** [comment]
Thanks for the help Cuong! Your commit looks great. Gonna merge

**Pull request merged**
